/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcoladistanze;

import java.io.IOException;
import static java.lang.Math.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import jfm.JavaFileManager;

/**
 *
 * @author MAALFING
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    List<Persona> vett;
    //JavaFileManager FM; //Grazie Paci

    public Frame() {
        initComponents();
        vett = new ArrayList();
//        FM = new JavaFileManager(System.getProperty("user.dir")+"/elenco.txt");
//        try {
//            FM.createNewFile();
//            FM.write("CIAO");
//        } catch (IOException ex) {
//            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
//        }

        vett.add(new Persona("Agnello", 45.693009, 9.179917, 250));
        vett.add(new Persona("Baccaglini", 45.696803, 9.087193, 286));
        vett.add(new Persona("Bianchi", 45.757238, 9.237426, 315));
        vett.add(new Persona("Bondesan", 45.679952, 9.185368, 245));
        vett.add(new Persona("Camagni", 45.731899, 9.126878, 340));
        vett.add(new Persona("~Cattaneo", 45.717384, 9.207714, 285));
        vett.add(new Persona("Consonni", 45.672975, 9.179287, 238));
        vett.add(new Persona("Conti", 45.677564, 9.168556, 234));
        vett.add(new Persona("D’Assaro", 45.685851, 9.102195, 271));
        vett.add(new Persona("De Maria", 45.731721, 9.158540, 326));
        vett.add(new Persona("Frigerio", 45.660039, 9.159194, 221));
        vett.add(new Persona("Ginisi", 45.738337, 9.135111, 339));
        vett.add(new Persona("Lauria", 45.752482, 9.246511, 264));
        vett.add(new Persona("Lucidera", 45.634366, 9.173865, 209));
        vett.add(new Persona("Marelli", 45.737407, 9.124352, 334));
        vett.add(new Persona("Marturano", 45.687445, 9.177291, 243));
        vett.add(new Persona("Mornatta", 45.686457, 9.177840, 245));
        vett.add(new Persona("Origgi", 45.655719, 9.175487, 225));
        vett.add(new Persona("Paci", 45.787147, 9.246910, 271));
        vett.add(new Persona("Porta", 45.671249, 9.075884, 250));
        vett.add(new Persona("Roncoroni", 45.738468, 9.139292, 340));
        vett.add(new Persona("Russo", 45.752356, 9.245676, 263));
        vett.add(new Persona("Saetti", 45.680642, 9.171187, 238));
        vett.add(new Persona("Soggiu", 45.634492, 9.174940, 209));
        vett.add(new Persona("Villa", 45.785359, 9.246000, 262));

        vett.add(new Persona("Classe", 45.687613, 9.181218, 249));
//        vett.add(new Persona("Atrio Rosso", 45.687191, 9.179684, 248));
//        vett.add(new Persona("Atrio Arancione", 45.687761, 9.181209, 249));
//        vett.add(new Persona("Atrio Giallo", 45.688070, 9.180375, 250));

        Citta cesano = new Citta(0, 0, 199, "Cesano Maderno", "MB");
        Citta lentate = new Citta(0, 0, 246, "Lentate sul Seveso", "MB");
        Citta merone = new Citta(0, 0, 282, "Merone", "CO");
        Citta cantu = new Citta(0, 0, 356, "Cantù", "CO");
        Citta cermenate = new Citta(0, 0, 295, "Cermenate", "CO");
        Citta lambrugo = new Citta(0, 0, 280, "Lambrugo", "CO");
        Citta cabiate = new Citta(0, 0, 233, "Cabiate", "CO");
        Citta arosio = new Citta(0, 0, 292, "Arosio", "CO");
        Citta mariano = new Citta(0, 0, 250, "Mariano Comense", "CO");
        Citta meda = new Citta(0, 0, 224, "Meda", "MB");
        Citta lazzate = new Citta(0, 0, 256, "Lazzate", "MB");
        Citta como = new Citta(0, 0, 200, "Como", "CO");
        Citta monza = new Citta(0, 0, 162, "Monza", "MB");
        Citta milano = new Citta(0, 0, 119, "Milano", "MI");

        for (int i = 0; i < vett.size(); i++) {
            jComboBox1.addItem(vett.get(i).nome);
            vett.get(i).lat = (vett.get(i).lat * PI) / 180;
            vett.get(i).lon = (vett.get(i).lon * PI) / 180;
        }

        for (int i = 0; i < vett.size(); i++) {
            jComboBox2.addItem(vett.get(i).nome);
        }

    }

    public String CD(Persona P1, Persona P2) {
        double Dz = 0;

        Dz = 6372 * (acos(sin(P1.lat) * sin(P2.lat) + cos(P1.lat) * cos(P2.lat) * cos(abs(P1.lon - P2.lon))));
        Dz = Math.ceil(Dz * 1000.0) / 1000.0;
        return Double.toString(Dz);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jButton1.setText("Calcola distanza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Da uno a molti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("Ordina");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton3.setText("Città");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 239, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(42, 42, 42)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jCheckBox1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Persona P1 = null, P2 = null;
        for (int i = 0; i < vett.size(); i++) {
            if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).toString().equals(vett.get(i).nome)) {
                P1 = vett.get(i);
            }
        }

        for (int i = 0; i < vett.size(); i++) {
            if (jComboBox2.getItemAt(jComboBox2.getSelectedIndex()).toString().equals(vett.get(i).nome)) {
                P2 = vett.get(i);
            }
        }

        jLabel1.setText(CD(P1, P2) + " km");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Persona P1 = null;
        for (int i = 0; i < vett.size(); i++) {
            if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).toString().equals(vett.get(i).nome)) {
                P1 = vett.get(i);
            }
        }

        if (!jCheckBox1.isSelected()) {
            jTextArea1.setText("");
            for (int i = 0; i < vett.size(); i++) {
                jTextArea1.setText(jTextArea1.getText() + vett.get(i).nome + ": " + CD(P1, vett.get(i)) + " km\n");

            }
        } else {
            List<Persona> tmp = vett;
            for (int i = 0; i < tmp.size() - 1; i++) {
                for (int j = 0; j < tmp.size() - i - 1; j++) {
                    if (Float.parseFloat(CD(P1, tmp.get(j))) > Float.parseFloat(CD(P1, tmp.get(j + 1)))) {
                        //swap arr[j+1] and arr[j]
                        Persona temp = tmp.get(j);
                        tmp.set(j, tmp.get(j + 1));
                        tmp.set(j + 1, temp);
                    }
                }
            }

            jTextArea1.setText("");
            for (int i = 0; i < tmp.size(); i++) {
                jTextArea1.setText(jTextArea1.getText() + tmp.get(i).nome + ": " + CD(P1, tmp.get(i)) + " km\n");

            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        List<Persona> tmp = vett;

        Persona P1 = null;
        for (int i = 0; i < vett.size(); i++) {
            if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).toString().equals(vett.get(i).nome)) {
                P1 = vett.get(i);
            }
        }

        if (jCheckBox1.isSelected()) {
            for (int i = 0; i < tmp.size() - 1; i++) {
                for (int j = 0; j < tmp.size() - i - 1; j++) {
                    if (Float.parseFloat(CD(P1, tmp.get(j))) > Float.parseFloat(CD(P1, tmp.get(j + 1)))) {
                        //swap arr[j+1] and arr[j]
                        Persona temp = tmp.get(j);
                        tmp.set(j, tmp.get(j + 1));
                        tmp.set(j + 1, temp);
                    }
                }
            }

            jTextArea1.setText("");
            for (int i = 0; i < tmp.size(); i++) {
                jTextArea1.setText(jTextArea1.getText() + tmp.get(i).nome + ": " + CD(P1, tmp.get(i)) + " km\n");

            }
        } else {
            jTextArea1.setText("");
            for (int i = 0; i < vett.size(); i++) {
                jTextArea1.setText(jTextArea1.getText() + vett.get(i).nome + ": " + CD(P1, vett.get(i)) + " km\n");

            }
        }


    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrameCitta FC = new FrameCitta(vett);
        FC.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
